name: Lint extension

on:
  pull_request:
    branches: [ master ]
    paths:
    - 'extension/**'

defaults:
  run:
    working-directory: extension

jobs:
  lint-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Npm install
      run: npm install
    - name: Verify install
      run: |
        ls ./src/css/generated/uk-tabfloater.css
        ls ./src/libs/uikit/uikit.min.js
        ls ./src/libs/uuid/uuidv4.min.js
        ls ./src/libs/webextension-polyfill/browser-polyfill.min.js
    - name: Lint
      run: npm run lint
  lint-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Npm install
      run: npm install
    - name: Verify install
      run: |
        dir ./src/css/generated/uk-tabfloater.css
        dir ./src/libs/uikit/uikit.min.js
        dir ./src/libs/webextension-polyfill/browser-polyfill.min.js
    - name: Lint
      run: npm run lint
