name: Release companion

on:
  push:
    tags:
      - 'v*_companion'

defaults:
  run:
    working-directory: companion

jobs:
  build-appimage-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build AppImage
      run: ./packaging/linux/build_appimage.sh
    - name: Upload AppImage to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./dist/*.AppImage
        file_glob: true
        overwrite: true
        tag: ${{ github.ref }}
#   upload-ppa-linux:
#     runs-on: ubuntu-20.04
#     steps:
#     - uses: actions/checkout@v2
#     - name: Install dependencies
#       run: sudo apt-get install cmake debhelper devscripts
#     - name: Import GPG key
#       env:
#         GPG_PRIVATE_KEY: ${{ secrets.TABFLOATER_GPG_PRIVATE_KEY }}
#       run: echo $GPG_PRIVATE_KEY | base64 --decode | gpg --batch --import
#     - name: Build DEB package and upload to PPA
#       run: ./packaging/linux/ppa_upload.sh
  build-windows-packages:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Build packages
      run: ./build.bat --package
    - name: Upload installer to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist\*.zip
        file_glob: true  
        overwrite: true
        tag: ${{ github.ref }}
    - name: Upload portable package to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist\*.zip
        file_glob: true  
        overwrite: true
        tag: ${{ github.ref }}
