name: Release companion

on:
  workflow_dispatch

defaults:
  run:
    working-directory: companion/packaging/linux

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ./build_appimage.sh
