name: Release companion

on:
  workflow_dispatch

defaults:
  run:
    working-directory: companion/

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ./packaging/linux/build_appimage.sh
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./dist/*.AppImage
        asset_name: mything
        overwrite: true
        tag: ${{ github.ref }}  
        body: "This is my release text"
